[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sw.js"
  to = "/404"
  status = 404

[[headers]]
  for = "/sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
